travis:
  secure:
    BINSTAR_TOKEN: sGVPLiYTe3J4fNoXn89LoQbGfVrBNOMYEj+RXgqhmL1AfCvJndheDmXRO5LzgRyZ9L7xy2t0aVz5bz3o/7rqChnYT10NPhYOW9Ccp1MOl7diy2ntRdNP+BsQGFAIgOY6aEzPSRzX5y9IjM1LCm+GNp2+hoKCWtXOQoRRYzQhR9DEYwugcAVbovsiv4X68fKuPbg425mGAnKtGGPJJurZPfyLzJ0bOXemLxQ8CsuvnrBUGe2jviy6EAWcZO3tFgwT1/IE34zfkCfiubnpSjPbf+u7Pka9Ni+nFby5zqeKZlj+kKiT7dRf5ebjw2eIgzJxKc/I1nirpgK4Le/mYsjcJJYRH4WexrYHdujhvZgb2sY7+4ien6t1llyAY0HMqdXn+7oH3hJ9ZGdxTP1A4sLn1vtNu6PXKz5ZbVeruAE9cDJgwAjfZF3D9P5ho7owMq4jMfGHyfLUs8SoDKjVw1Hd3GktERqw7M+eqE7f7ZGh+igik0nwrF5nEIl0+N2L8Qv6KIjC7TE3MQAQ1T/C09fNCov36zjwzGS/tbJiNVZ3kEvRHnn2p4wk1cocPROMRjNHln3NSeANag55BBVESIwlqOM2CjnB4SsqtNaJL+s+m5Q3MdwPpOBk4QcJbpLUFzMKEbfssnSHISE5XXf6EGDdAhAfO/BbwGAPXtZkowotok4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
